import {
  defaultDeliveryDeps,
  runDueCampaignDeliveries,
  syncActiveCampaignBookings,
  type BookingSweepResult,
  type SweepResult,
} from '@/lib/campaign/delivery-service';
import {
  CRON_GENERATION_BUDGET_MS,
  emptyGenerationSweep,
  releaseQueuedForInactiveCampaigns,
  runQueuedCampaignGenerationsExclusively,
  type ExclusiveGenerationSweep,
} from '@/lib/campaign/generation-queue';
import { prisma } from '@/lib/prisma';
import { getAppTimeZone } from '@/lib/time';

/**
 * The recurring dispatch sweep behind `/api/cron`.
 *
 * Every sweep runs the campaign work in steps, each wrapped so a failure in one
 * cannot stop the next. The cheap, time-critical work goes first, so a slow
 * generation can never delay a send or push it past the request's ceiling:
 *
 * 1. **Booking sync.** Approval and activation already book their days, so this
 *    is the self-healing net — it books an approved day whose booking was missed
 *    (a crash, WhatsApp configured later), re-pins or withdraws a booking whose
 *    poster changed, and marks missed days. Narrow, bounded queries; it never
 *    sends. Running it before the send pass lets a day it books that is already
 *    due go out on this same tick, through the same gate.
 * 2. **Due deliveries.** Sends the `CampaignDelivery` rows whose moment has come.
 *    Failures are recorded on each delivery row and the sweep carries on, so a
 *    failure on day 5 cannot stop day 6.
 * 3. **Queued poster generation.** `ContentCalendar.generationStatus = QUEUED`
 *    is the queue (campaign days only); an operator queues a batch from the
 *    board and may close the tab, and this drains it a few days per tick. First
 *    the queue of campaigns no longer ACTIVE is released. Then, only if no other
 *    sweep is generating (an advisory lock), days are started until
 *    `CRON_GENERATION_BUDGET_MS` has passed; the one in flight finishes.
 *
 * The retired daily poster maker's phases (held-back sends, release at each
 * client's delivery minute, and the pre-generation backlog) no longer run. Its
 * calendar rows — those with no campaign — are kept as data and never touched
 * here.
 */

export interface DispatchSummary {
  ranAt: string;
  timeZone: string;
  /** Campaign days delivered this sweep. */
  campaignSent: number;
  campaignFailed: number;
  campaignSkipped: number;
  /** Campaign posters generated by the server-side queue this sweep. */
  campaignGenerated: number;
  campaignGenerationFailed: number;
  /** Campaign days booked (or re-pinned to a newly approved poster) by this sweep's booking sync. */
  campaignBooked: number;
  /** Another sweep was already generating, so this one skipped generation. */
  campaignGenerationBusy: boolean;
}

/** The sweep's steps, replaceable in tests (which check their order and isolation). */
export interface DispatchSteps {
  syncBookings(now: Date): Promise<BookingSweepResult>;
  runDeliveries(now: Date): Promise<SweepResult>;
  releaseInactiveQueues(): Promise<number>;
  /** `budgetMs`: what is left of the generation budget once the steps before it ran. */
  runGeneration(now: Date, budgetMs: number): Promise<ExclusiveGenerationSweep>;
}

export const defaultDispatchSteps: DispatchSteps = {
  syncBookings: (now) => syncActiveCampaignBookings(prisma, defaultDeliveryDeps({ now: () => now })),
  runDeliveries: (now) => runDueCampaignDeliveries(prisma, defaultDeliveryDeps({ now: () => now })),
  releaseInactiveQueues: () => releaseQueuedForInactiveCampaigns(prisma),
  runGeneration: (now, budgetMs) => runQueuedCampaignGenerationsExclusively(prisma, { now, budgetMs }),
};

export async function executeIntervalDispatch(
  now: Date = new Date(),
  overrides: Partial<DispatchSteps> = {},
): Promise<DispatchSummary> {
  const timeZone = getAppTimeZone();
  const steps: DispatchSteps = { ...defaultDispatchSteps, ...overrides };
  // The generation budget counts from the start of the sweep, so slow sends
  // leave less time for generation rather than pushing the sweep past its ceiling.
  const sweepStartedAt = Date.now();

  // ---- 1. Booking sync --------------------------------------------------------
  let campaignBookings: BookingSweepResult = { considered: 0, booked: 0, repinned: 0, cancelled: 0, missed: 0 };
  try {
    campaignBookings = await steps.syncBookings(now);
  } catch (error) {
    console.error('[ace:cron] campaign booking sync failed', error instanceof Error ? error.message : error);
  }

  // ---- 2. Due campaign deliveries -------------------------------------------
  let campaignDeliveries: SweepResult = { considered: 0, sent: [], failed: [], skipped: [] };
  try {
    campaignDeliveries = await steps.runDeliveries(now);
  } catch (error) {
    console.error('[ace:cron] campaign delivery sweep failed', error instanceof Error ? error.message : error);
  }

  // ---- 3. Queued campaign poster generation --------------------------------
  //
  // Last, and bounded three ways: days per tick, a wall-clock budget, and one
  // sweep at a time. Each day is an image model call plus a composite, a text
  // check and two Drive writes, and the sweep is one HTTP request with a ceiling.
  try {
    await steps.releaseInactiveQueues();
  } catch (error) {
    console.error('[ace:cron] releasing paused campaigns\' queues failed', error instanceof Error ? error.message : error);
  }
  let campaignGeneration: ExclusiveGenerationSweep = { ...emptyGenerationSweep(), lockHeld: false };
  try {
    campaignGeneration = await steps.runGeneration(now, Math.max(0, CRON_GENERATION_BUDGET_MS - (Date.now() - sweepStartedAt)));
  } catch (error) {
    console.error('[ace:cron] campaign generation sweep failed', error instanceof Error ? error.message : error);
  }

  console.info(
    `[ace:cron] tz=${timeZone} generated=${campaignGeneration.generated.length}${campaignGeneration.lockHeld ? ' (another sweep is generating)' : ''} ` +
      `generationFailed=${campaignGeneration.failed.length} booked=${campaignBookings.booked + campaignBookings.repinned} ` +
      `sent=${campaignDeliveries.sent.length} failed=${campaignDeliveries.failed.length} skipped=${campaignDeliveries.skipped.length}`,
  );

  return {
    ranAt: now.toISOString(),
    timeZone,
    campaignSent: campaignDeliveries.sent.length,
    campaignFailed: campaignDeliveries.failed.length,
    campaignSkipped: campaignDeliveries.skipped.length,
    campaignGenerated: campaignGeneration.generated.length,
    campaignGenerationFailed: campaignGeneration.failed.length,
    campaignBooked: campaignBookings.booked + campaignBookings.repinned,
    campaignGenerationBusy: campaignGeneration.lockHeld,
  };
}
