-- Hold every generated poster for operator approval before it can be broadcast,
-- and let a whole campaign be pre-generated ahead of its delivery days.
--
-- Hand-authored rather than generated by `prisma migrate dev`, for the same reason
-- as the three migrations before it: that command wants a live database plus a
-- shadow database to diff against, and neither exists on a development machine here.
--
-- Both columns are nullable with no default, so PostgreSQL records them in the
-- catalogue and rewrites no rows.

-- AlterTable
ALTER TABLE "ContentCalendar" ADD COLUMN     "approvedAt" TIMESTAMP(3);
ALTER TABLE "ContentCalendar" ADD COLUMN     "generationQueuedAt" TIMESTAMP(3);

-- Backfill. This is the load-bearing statement in the migration, and unlike the
-- `sendAfter` migration null is emphatically NOT the correct value for existing
-- rows.
--
-- From this deploy onward the dispatch sweep refuses to release a poster whose
-- `approvedAt` is null. Every row already in this table belongs to a campaign a
-- client is paying for and that nobody is going to retro-approve, so leaving them
-- null would stop the entire fleet's delivery on the next sweep — silently, since
-- an unapproved row is skipped rather than failed.
--
-- `createdAt` rather than `now()` so the timestamp does not claim a human looked
-- at these on deploy day. It reads as "approved when it was written", which is the
-- honest description of the behaviour these rows were created under.
UPDATE "ContentCalendar" SET "approvedAt" = "createdAt";

-- Serves the backlog phase: PENDING rows the operator has asked to pre-generate.
-- `generationQueuedAt` is null for all but the handful of rows in flight at any
-- moment, so this stays small even as the table grows.
-- CreateIndex
CREATE INDEX "ContentCalendar_deliveryStatus_generationQueuedAt_idx" ON "ContentCalendar"("deliveryStatus", "generationQueuedAt");
