-- Hold the WhatsApp broadcast back by a random few minutes after generation.
--
-- Hand-authored rather than generated by `prisma migrate dev`, for the same reason
-- as the two migrations before it: that command wants a live database plus a shadow
-- database to diff against, and neither exists on a development machine here.
--
-- No table rewrite. The column is nullable with no default, so PostgreSQL records
-- it in the catalogue and touches no existing row — and null is the correct value
-- for all of them. A null "sendAfter" means "no scheduled send", which is exactly
-- what every row written before this migration is: either already delivered, or a
-- historical failure that must not start delivering on its own.
--
-- The index is the send phase's whole query plan: once a minute it asks for
-- GENERATED rows whose sendAfter has passed. Unlike the existing
-- (scheduledDate, deliveryStatus) index this one is deliberately not date-scoped —
-- a 23:58 poster held for eight minutes is due at 00:06 the following day.

-- AlterTable
ALTER TABLE "ContentCalendar" ADD COLUMN     "sendAfter" TIMESTAMP(3);

-- CreateIndex
CREATE INDEX "ContentCalendar_deliveryStatus_sendAfter_idx" ON "ContentCalendar"("deliveryStatus", "sendAfter");
