-- Carry an uploaded reference poster's own geometry, so generated creatives can
-- follow the template instead of the nearest of fifteen built-in compositions.
--
-- Hand-authored rather than generated by `prisma migrate dev`, for the same reason
-- as the migrations before it: that command wants a live database plus a shadow
-- database to diff against, and neither exists on a development machine here.
--
-- All three columns are nullable with no default, so PostgreSQL records them in
-- the catalogue and rewrites no rows. On a library of a few hundred templates
-- this is instant.
--
-- Deliberately NOT backfilled, and the important one is `layoutApprovedAt`.
-- Null there means "no human has confirmed this layout matches its template",
-- which is true of every existing row by construction — extraction had not been
-- built when they were uploaded. Backfilling it to `now()` would publish
-- geometry nobody has seen onto every client in the vertical, which is the exact
-- failure the column exists to prevent. Existing templates therefore keep
-- behaving precisely as they do today: their mapped `archetype` decides the
-- layout, and the new columns sit unread until an operator works through the
-- gallery.

-- AlterTable
ALTER TABLE "CategoryTemplate" ADD COLUMN     "layoutSpec" JSONB,
ADD COLUMN     "layoutReading" TEXT,
ADD COLUMN     "layoutApprovedAt" TIMESTAMP(3);

-- Serves generation's preferred path: the approved specs for one vertical, in
-- upload order. Partial in effect rather than declaration — `layoutApprovedAt`
-- is null for every row until templates are reviewed, so the index stays small
-- while the library is being worked through.
-- CreateIndex
CREATE INDEX "CategoryTemplate_categoryId_layoutApprovedAt_idx" ON "CategoryTemplate"("categoryId", "layoutApprovedAt");
