import Link from 'next/link';

import { Check, Circle, ExternalLink, Palette, Sparkles, UserCog } from 'lucide-react';

import { Button } from '@/components/ui/button';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { cn } from '@/lib/utils';

/**
 * Onboarding orientation for the demo workspace.
 *
 * Exists because poster identity — the logo, tagline, website and phone printed
 * on every creative — is only editable on `/admin/clients/{id}/brand`, and
 * nothing on the demo page pointed there. Operators were generating demo
 * posters with a fallback wordmark and no website without ever being told why.
 *
 * Deliberately a *server* component: it renders status and one link, so there
 * is no reason to ship it to the browser. It also deliberately does not edit
 * anything — the brand page stays the single editing surface, so validation and
 * server actions are never duplicated.
 */

export interface IdentityField {
  label: string;
  value: string | null;
  /** Shown under a missing field to explain what the renderer does instead. */
  fallback: string;
}

/**
 * The four columns composited onto every poster.
 *
 * Note these live on `Client` as real columns, NOT inside `brandGuideline` —
 * the tokenizer rewrites that JSON wholesale, so an operator-uploaded logo has
 * to survive a re-extraction. Do not go looking for them in the guideline.
 */
export function identityFields(client: {
  logoUrl: string | null;
  websiteUrl: string | null;
  displayPhone: string | null;
  brandTagline: string | null;
}): IdentityField[] {
  return [
    {
      label: 'Logo',
      value: client.logoUrl,
      fallback: 'a generated wordmark is used instead',
    },
    {
      label: 'Website',
      value: client.websiteUrl,
      fallback: 'the contact bar omits the website cell',
    },
    {
      label: 'Display phone',
      value: client.displayPhone,
      fallback: 'derived from the WhatsApp number',
    },
    {
      label: 'Tagline',
      value: client.brandTagline,
      fallback: 'the line under the logo is omitted',
    },
  ];
}

/** Three-step orientation strip across the top of the workspace. */
export function DemoSetupProgress({
  identityComplete,
  hasBrandTokens,
  hasCalendar,
}: {
  identityComplete: boolean;
  hasBrandTokens: boolean;
  hasCalendar: boolean;
}) {
  const steps = [
    { label: 'Brand identity', hint: 'Logo, website, phone', done: identityComplete },
    { label: 'Brand tokens', hint: 'Palette and fonts', done: hasBrandTokens },
    { label: 'Ready to generate', hint: 'Send a creative', done: hasCalendar },
  ];

  return (
    <ol className="flex flex-wrap items-center gap-x-2 gap-y-2 rounded-xl border border-border bg-secondary/40 px-4 py-3">
      {steps.map((step, index) => (
        <li key={step.label} className="flex items-center gap-2">
          <span
            className={cn(
              'flex h-5 w-5 shrink-0 items-center justify-center rounded-full border text-[10px] font-semibold',
              step.done
                ? 'border-success/40 bg-success/15 text-success-ink'
                : 'border-border text-muted-foreground',
            )}
          >
            {step.done ? <Check className="h-3 w-3" /> : index + 1}
          </span>

          <span className="flex flex-col leading-tight">
            <span
              className={cn(
                'text-[11px] font-medium',
                step.done ? 'text-foreground' : 'text-muted-foreground',
              )}
            >
              {step.label}
            </span>
            <span className="text-[10px] text-muted-foreground/70">
              {step.done ? 'Done' : step.hint}
            </span>
          </span>

          {index < steps.length - 1 && (
            <span aria-hidden className="mx-1 h-px w-6 bg-border sm:w-10" />
          )}
        </li>
      ))}
    </ol>
  );
}

/**
 * Read-only checklist of the four poster-identity fields, with the one link to
 * the page that edits them.
 */
export function BrandIdentityCard({
  tenantId,
  companyName,
  fields,
}: {
  tenantId: string;
  companyName: string;
  fields: IdentityField[];
}) {
  const missing = fields.filter((field) => !field.value);

  return (
    <Card className={missing.length > 0 ? 'border-warning/30' : undefined}>
      <CardHeader className="flex-row items-start justify-between gap-4 space-y-0">
        <div className="space-y-1">
          <CardTitle className="flex items-center gap-2">
            <UserCog className="h-4 w-4 text-brand-to" />
            Brand identity
          </CardTitle>
          <CardDescription>
            Composited onto every creative as real type — never generated by the image
            model, because a misspelt phone number reaches the client.
          </CardDescription>
        </div>

        <Button asChild variant="outline" size="sm">
          <Link
            href={`/admin/clients/${tenantId}/brand?return=${encodeURIComponent(
              `/admin/demo?tenant=${tenantId}`,
            )}`}
          >
            <Palette className="h-4 w-4" />
            {missing.length > 0 ? 'Configure' : 'Edit'}
            <ExternalLink className="h-3 w-3" />
          </Link>
        </Button>
      </CardHeader>

      <CardContent className="space-y-3">
        <dl className="grid grid-cols-1 gap-x-6 gap-y-2 sm:grid-cols-2">
          {fields.map((field) => (
            <div key={field.label} className="flex items-start gap-2">
              {field.value ? (
                <Check className="mt-0.5 h-3.5 w-3.5 shrink-0 text-success-ink" />
              ) : (
                <Circle className="mt-0.5 h-3.5 w-3.5 shrink-0 text-warning-ink" />
              )}
              <div className="min-w-0 space-y-0.5">
                <dt className="text-[11px] font-medium text-foreground">{field.label}</dt>
                <dd
                  className={cn(
                    'truncate text-[10px]',
                    field.value ? 'font-mono text-muted-foreground' : 'text-warning-ink',
                  )}
                  title={field.value ?? undefined}
                >
                  {field.value ?? `Not set — ${field.fallback}`}
                </dd>
              </div>
            </div>
          ))}
        </dl>

        {missing.length > 0 && (
          <p className="flex items-start gap-2 rounded-lg border border-warning/25 bg-warning/5 p-2.5 text-[11px] text-warning-ink">
            <Sparkles className="mt-0.5 h-3.5 w-3.5 shrink-0" />
            <span>
              {companyName} can still generate creatives — the renderer degrades rather
              than failing — but {missing.length === 1 ? 'this field' : 'these fields'} will
              fall back:{' '}
              <span className="font-medium">
                {missing.map((field) => field.label).join(', ')}
              </span>
              .
            </span>
          </p>
        )}
      </CardContent>
    </Card>
  );
}
