-- Distinguish a manually-uploaded poster from one the creative pipeline drew.
--
-- Hand-authored rather than generated by `prisma migrate dev`, for the same
-- reason as every migration before it: that command wants a live database plus a
-- shadow database to diff against, and neither exists on a development machine
-- here.
--
-- The column is NOT NULL with a default, which PostgreSQL 11+ records in the
-- catalogue rather than rewriting the table — so this is a metadata-only change
-- however many campaign days are already stored.
--
-- `PIPELINE` is the correct value for every existing row, and unlike the
-- `approvedAt` migration there is nothing to backfill: each one was seeded
-- PENDING and rendered by `runCreativePipeline`, which is exactly what the
-- default says. Nothing reads this column until the manual upload path writes
-- the other value, so applying it changes no behaviour at all.

-- CreateEnum
CREATE TYPE "ContentSourceType" AS ENUM ('PIPELINE', 'MANUAL_UPLOAD');

-- AlterTable
ALTER TABLE "ContentCalendar" ADD COLUMN "sourceType" "ContentSourceType" NOT NULL DEFAULT 'PIPELINE';
