-- Retire the fifteen built-in poster compositions.
--
-- Every poster is now drawn from a reference template an operator uploaded,
-- extracted and approved. `src/lib/poster/archetypes.tsx` and the catalogue that
-- described its compositions are gone, so nothing reads either column.
--
-- Hand-authored rather than generated by `prisma migrate dev`, for the same
-- reason as the migrations before it.
--
-- **IRREVERSIBLE, and unlike the migration before it this destroys operator
-- decisions**: which of the fifteen a reference poster was said to resemble, and
-- which one a given day was rendered in. Nothing recreates them. Take a dump
-- first — `./scripts/backup-db.sh`, see DEPLOY_VPS.md.
--
-- Safe here specifically because Docker Compose stops the old container before
-- starting the new one, so no process is left running that still selects these.
-- A rolling deploy would need the code released first and this held back.
--
-- Deliberately separate from 20260823120000_calendar_template_pin. That one is
-- additive and reversible; this one is not, and mixing them would mean a single
-- statement failing anywhere in the pair leaves the schema half-moved with no
-- clean way back.
DROP INDEX "CategoryTemplate_categoryId_archetype_idx";
ALTER TABLE "CategoryTemplate" DROP COLUMN "archetype";
ALTER TABLE "ContentCalendar" DROP COLUMN "posterArchetype";
