-- Let an operator state which layout each reference poster represents, so the
-- generator can draw a vertical's compositions from its own uploaded library.
--
-- Hand-authored rather than generated by `prisma migrate dev`, for the same reason
-- as the migrations before it: that command wants a live database plus a shadow
-- database to diff against, and neither exists on a development machine here.
--
-- Nullable with no default, so PostgreSQL records it in the catalogue and rewrites
-- no rows.
--
-- Deliberately NOT backfilled, unlike the approval migration. Null is the correct
-- value for every existing template: nobody has said what any of them represent,
-- and inventing an answer would put layouts into rotation that no one chose. An
-- unmapped template keeps behaving exactly as it did — stored, shown in the
-- gallery, ignored by the renderer.

-- AlterTable
ALTER TABLE "CategoryTemplate" ADD COLUMN     "archetype" TEXT;

-- Serves the generator's lookup: the mapped layouts for one vertical. Partial in
-- effect rather than declaration — `archetype` is null for every row until an
-- operator works through the gallery, so the index stays small in the meantime.
-- CreateIndex
CREATE INDEX "CategoryTemplate_categoryId_archetype_idx" ON "CategoryTemplate"("categoryId", "archetype");
