-- Background removal for uploaded client logos.
--
-- Hand-authored rather than generated by `prisma migrate dev`: that command wants
-- a live database plus a shadow database to diff against, and neither exists on a
-- development machine here — the only Postgres is the `db` service on the VPS,
-- where `docker-entrypoint.sh` runs `migrate deploy`. Three nullable columns and
-- one defaulted boolean need no backfill and take no table rewrite, so the
-- generated form would be these exact statements.
--
-- Existing rows read as "logo present, never keyed", which is true of every logo
-- uploaded before this migration. The operator re-processes them from the brand
-- panel; nothing here changes a logo that is already live.

-- AlterTable
ALTER TABLE "Client" ADD COLUMN     "logoOriginalUrl" TEXT,
ADD COLUMN     "logoOriginalDriveFileId" TEXT,
ADD COLUMN     "logoBackgroundRemoved" BOOLEAN NOT NULL DEFAULT false;
