-- Operator-supplied fal.ai key, and the spend attribution it needs.
--
-- Hand-authored rather than generated by `prisma migrate dev`, for the same reason as
-- 20260806120000: that command wants a live database plus a shadow database to diff
-- against, and neither exists on a development machine here — the only Postgres is the
-- `db` service on the VPS, where `docker-entrypoint.sh` runs `migrate deploy`.
--
-- Neither statement rewrites a table. "AppSetting" is new and starts empty; its single
-- row is created lazily by the first save, so an install that never uses the panel
-- never grows one. "UsageEvent"."keySource" is added with a non-volatile default, which
-- PostgreSQL 11+ records in the catalogue instead of writing every existing row — and
-- PLATFORM is the truth for all of them, since every call recorded before this migration
-- was billed to the platform's own credentials.

-- CreateEnum
CREATE TYPE "UsageKeySource" AS ENUM ('PLATFORM', 'BYO');

-- CreateTable
CREATE TABLE "AppSetting" (
    "id" TEXT NOT NULL DEFAULT 'singleton',
    "falKeyCipher" TEXT,
    "falKeyLast4" TEXT,
    "falKeyLabel" TEXT,
    "falKeyUpdatedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "AppSetting_pkey" PRIMARY KEY ("id")
);

-- AlterTable
ALTER TABLE "UsageEvent" ADD COLUMN     "keySource" "UsageKeySource" NOT NULL DEFAULT 'PLATFORM';
