-- Pin each campaign day to the reference template it must be laid out from, and
-- make a template's name the thing a spreadsheet can address it by.
--
-- Hand-authored rather than generated by `prisma migrate dev`, for the same reason
-- as the migrations before it: that command wants a live database plus a shadow
-- database to diff against, and neither exists on a development machine here.
--
-- Read the order below before editing it. `migrate deploy` runs from
-- docker-entrypoint.sh under `set -e`, *before* Next.js binds a port — a statement
-- that fails here does not degrade the console, it stops the container serving at
-- all and Caddy's health check never passes. Section 3 is the only part that can
-- fail on real data, and it is written to be unfailable rather than to be pretty.

-- ---------------------------------------------------------------------------
-- 1. `theme` becomes optional
-- ---------------------------------------------------------------------------
--
-- The import sheet no longer carries a theme column: a day's angle now comes out
-- of its caption, and its layout out of the template it names. The column stays
-- because the calendar generator and the demo panel both still write one, and
-- `ensurePosterCopy` still uses it when it is there.
--
-- Dropping NOT NULL is a catalogue edit — no rewrite, no backfill, and every
-- existing row keeps the theme it was written with. Deliberately NOT cleared:
-- those themes describe copy that is still on the row beside them.
ALTER TABLE "ContentCalendar" ALTER COLUMN "theme" DROP NOT NULL;

-- ---------------------------------------------------------------------------
-- 2. The per-day template pin
-- ---------------------------------------------------------------------------
--
-- A foreign key rather than a copy of the template's name, which is the whole
-- reason names become renameable in section 3: a stored name would go stale the
-- instant an operator corrected a typo, and the day would quietly lose its
-- layout months after anyone last touched it. The id never moves.
--
-- SetNull, and neither of the other two:
--   Cascade would let deleting one reference poster delete a paying client's
--     campaign days.
--   Restrict would refuse to delete any template a sheet had ever named, turning
--     "this reference was a mistake" into a problem with no fix in the console.
-- SetNull degrades the day to the vertical's deterministic rotation, which is
-- exactly what an AI-seeded day gets anyway.
--
-- Nullable with no default, so ADD COLUMN rewrites nothing.
ALTER TABLE "ContentCalendar" ADD COLUMN     "posterTemplateId" TEXT;

-- Serves the SET NULL itself, not a query anyone writes. Without it every
-- CategoryTemplate delete sequentially scans ContentCalendar looking for
-- referencing rows — and deleting a vertical cascades up to a hundred templates,
-- so that is a hundred full scans of the fleet's whole calendar in one statement.
CREATE INDEX "ContentCalendar_posterTemplateId_idx" ON "ContentCalendar"("posterTemplateId");

ALTER TABLE "ContentCalendar" ADD CONSTRAINT "ContentCalendar_posterTemplateId_fkey"
    FOREIGN KEY ("posterTemplateId") REFERENCES "CategoryTemplate"("id")
    ON DELETE SET NULL ON UPDATE CASCADE;

-- ---------------------------------------------------------------------------
-- 3. Template names become unique within a vertical
-- ---------------------------------------------------------------------------
--
-- The load-bearing section. A sheet chooses a layout by typing the template's
-- name, so two templates in one vertical sharing a name is not untidy, it is
-- ambiguous: the import has no way to know which one was meant.
--
-- Duplicates may well exist. `label` has been the uploaded filename minus its
-- extension since the table was created and has never carried a constraint of any
-- kind, so every re-upload of the same file, every second camera roll's
-- IMG_2481.jpg, and every file whose name was nothing but an extension (all of
-- which became the literal string 'Untitled') is a collision waiting here. This
-- deployment happens to be clean, checked before writing this — but a migration
-- that only works on one database is not a migration.
--
-- They are renamed into the same suffix form the uploader now uses: `cafe_poster`,
-- `cafe_poster-2`, `cafe_poster-3`. Oldest keeps the bare name, ordered by
-- createdAt then id so a same-millisecond tie still resolves the same way twice.
--
-- The loop is not decoration. One pass is not enough: a vertical holding
-- 'poster', 'poster' and an unrelated 'poster-2' renames the second 'poster' to
-- 'poster-2' and lands on the row already called that. Each pass strictly
-- lengthens every label it moves and can only collide with a name that already
-- existed, so the set it can land on shrinks and the loop terminates — but a
-- migration that could in principle spin forever must not be able to, hence the
-- pass cap and the sweep after it.
--
-- Labels are NOT truncated to make room for the suffix, even though the uploader
-- caps new ones at 120 characters. Truncating is precisely how two different
-- 120-character names become one name, which is the thing this section exists to
-- prevent. An over-long legacy label is cosmetic, and the rename control fixes it
-- the first time anyone looks at that vertical.
DO $$
DECLARE
  moved integer;
  pass  integer := 0;
BEGIN
  LOOP
    WITH ranked AS (
      SELECT "id", "label",
             row_number() OVER (
               PARTITION BY "categoryId", "label"
               ORDER BY "createdAt", "id"
             ) AS seq
      FROM "CategoryTemplate"
    ),
    renamed AS (
      UPDATE "CategoryTemplate" AS t
      SET "label" = r."label" || '-' || r.seq
      FROM ranked r
      WHERE t."id" = r."id" AND r.seq > 1
      RETURNING t."id"
    )
    SELECT count(*) INTO moved FROM renamed;

    pass := pass + 1;
    EXIT WHEN moved = 0 OR pass >= 20;
  END LOOP;
END $$;

-- Belt and braces. If twenty passes somehow left a collision standing, break it
-- with the row's own id, which cannot collide with anything. Not expected to match
-- a row; it is here so that CREATE UNIQUE INDEX below cannot be the statement that
-- stops the container from booting.
UPDATE "CategoryTemplate" AS t
SET "label" = t."label" || ' (' || left(t."id", 8) || ')'
WHERE EXISTS (
  SELECT 1 FROM "CategoryTemplate" AS other
  WHERE other."categoryId" = t."categoryId"
    AND other."label"      = t."label"
    AND (other."createdAt", other."id") < (t."createdAt", t."id")
);

-- Case-SENSITIVE, matching @@unique([categoryId, label]) in schema.prisma. Prisma
-- cannot express a functional index, and a shadow one it does not know about is a
-- trap for whoever next runs `migrate diff`. The application layer carries the
-- case-insensitive half: `renameVerticalTemplate` refuses a name differing from an
-- existing one only by case, and the importer reports a name matching two
-- templates rather than picking one. That leaves exactly one gap — case variants
-- predating this migration — and the importer names them instead of guessing.
CREATE UNIQUE INDEX "CategoryTemplate_categoryId_label_key" ON "CategoryTemplate"("categoryId", "label");
